// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibmjjnbkhxfbyfprypxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlibWpqbmJraHhmYnlmcHJ5cHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTYxODMsImV4cCI6MjA3Mjg5MjE4M30.wb6sN-CVFS3laaoio0PK-fzUkzg5AymBPOQlux3kY6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});